logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    #root: DEBUG

server:
  port: 8081

jwt:
  expiration: 86400000
  secret-key: VraieSuperCléJWTTrèsLongueEtComplexe1234567890!

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sambre
    username: postgres
    password: sambre-passe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: Contacts@samretogo.com
    password: fylx upcc etkh sbze
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

smsvas:
  url: "https://smsvas.fr/api/sms"
  username: "teemirlaurent@yahoo.fr"
  password: "smsvas@2020"
  sender: "SAMRE"
  token : "9-7c41-4a4c-816c-8b7f3"
