logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    #org.springframework.security: DEBUG
    #root: DEBUG

server:
  port: 8081

jwt:
  expiration: 86400000
  secret-key: VraieSuperCléJWTTrèsLongueEtComplexe1234567890!

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sambre
    username: postgres
    password: sambre-passe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
